apiVersion: v1
entries:
  sentry:
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-02-02T20:14:33.426122716Z"
    description: A Helm chart for Kubernetes
    digest: 5fdead5f5f5dcd046a15719959596b740a5590e9e7d43b9739cf9fd83ecdb3f5
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/charts/sentry-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-02-02T20:14:33.425110811Z"
    description: A Helm chart for Kubernetes
    digest: 5e8a0760077fa04a6066e4da308500fc5406490fefe2e2eee03e484199629632
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/charts/sentry-0.1.0.tgz
    version: 0.1.0
  sentry-db:
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-02-02T20:14:33.452516743Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - condition: rabbitmq-ha.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: 92c965771faca9a6e2fc9a1c9a8bfa7c7037e20c60853105823b4248d0dbe3bc
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/charts/sentry-db-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-02-02T20:14:33.438354875Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    description: A Helm chart for Kubernetes
    digest: e651175dfd336736adbc2dbc423f9d80d79a3771e5af7f88ec5b099e24c72229
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/charts/sentry-db-0.1.0.tgz
    version: 0.1.0
generated: "2020-02-02T20:14:33.423959605Z"
