apiVersion: v1
entries:
  sentry:
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-02-02T20:36:13.424930394Z"
    description: A Helm chart for Kubernetes
    digest: 0da209fcf559a3aa66ef7715cf6327da2337e3739fff89e06a25d2e6a1488765
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.2.1.tgz
    version: 0.2.1
  sentry-db:
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-02-02T20:36:13.4401834Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - condition: rabbitmq-ha.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: ca96424a03a019c13e38bfb1a870081f8ade5b1503b493925732c0b8000d11b0
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-db-0.2.1.tgz
    version: 0.2.1
generated: "2020-02-02T20:36:13.423800993Z"
